### ISSUE TITLE
Modal.Py Issue

### ISSUE THREAD

**Issue by aggiefury101** [rmahendra9/NCAA-March-Madness-Bracket-Predictor#1]
Love your script, but i'm running in to List Index Out of Range error when comparing Gonzaga Georgia State. Am I missing something?

**Comment by rmahendra9** [comment]
One issue could be that the data you scraped from sportsreference has school names spelled differently that the ones on kenpom. For example, Georiga State might be Georgia St on kenpom, so it would throw an error. I fixed this manually in NCAA_Game_Log and MM-Pyth, so you should use those datasets when running the model. In any case, when running the model, make sure to wrap each school name with quotation marks, so it would be python model.py "Gonzaga" "Georgia State". Hopefully that helps!
